version: "3"
services:
  ros2:
    image: kaiaai/kaiaai:iron
    container_name: makerspet
    ports:
      - "8888:8888/udp"
      - "4430:4430/tcp"
    environment:
      - "DISPLAY=host.docker.internal:0.0"
      - "LIBGL_ALWAYS_INDIRECT=0"
#   stdin_open: true
#   tty: true
#   command: /bin/bash
#   entrypoint: ["/bin/bash"]